name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build_linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Установка зависимостей
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      # Генерация проекта с использованием CMake
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      # Сборка проекта
      - run: cmake --build .

      # Запуск тестов
      - run: cmake --build . --target test

      # Упаковка проекта
      - run: cmake --build . --target package

      # Создание релиза
      - name: Create Release for Linux
        id: create_release_linux
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }} for Linux
          draft: false
          prerelease: false

      # Загрузка артефактов релиза
      - name: Upload Release Asset for Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}
          asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true


       # Установка Boost
      - name: Install Boost
        run: choco install boost-msvc-14.2 --version=1.74.0 --install-arguments="'INSTALLDIR=C:\\local\\boost_1_74_0'"
        
      - name: Check Boost Installation
        run: dir "C:/local/boost_1_74_0"
      # Установка Visual Studio Build Tools и CMake
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional" --yes

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

      # Генерация проекта с использованием CMake
      - run: cmake . -G "Visual Studio 17 2022" -A x64 -DPATCH_VERSION=${{ github.run_number }}

      # Сборка проекта
      - run: cmake --build . --config Release

      # Копирование Boost DLL рядом с тестами
      - name: Copy Boost DLLs
        run: |
          dir "C:/Program Files/boost/boost_1_74_0/lib64-msvc-14.2"
          copy "C:/Program Files/boost/boost_1_74_0/lib64-msvc-14.2/*.dll" "./Release"

      # Запуск тестов
      - run: ctest --output-on-failure --build-config Release


      # Создание релиза для Windows
      - name: Create Release for Windows
        id: create_release_windows
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}-windows
          release_name: Release ${{ github.run_number }} for Windows
          draft: false
          prerelease: false

      # Загрузка артефактов релиза для Windows
      - name: Upload Release Asset for Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_windows.outputs.upload_url }}
          asset_path: ./Release/helloworld-0.0.${{ github.run_number }}-win64.zip
          asset_name: helloworld-0.0.${{ github.run_number }}-win64.zip
          asset_content_type: application/zip
